/**
 * Miles Morales Spider-Web & Venom Effect
 * Handles the dynamic canvas webbing between floating binary elements.
 */

(function() {
    const canvas = document.getElementById('web-canvas');
    if (!canvas) return;

    const ctx = canvas.getContext('2d');

    // Sync canvas size with window
    function resize() {
        canvas.width = window.innerWidth;
        canvas.height = window.innerHeight;
    }
    window.addEventListener('resize', resize);
    resize();

    function drawSpiderWebs() {
        ctx.clearRect(0, 0, canvas.width, canvas.height);
        
        // Grab the floating units generated by script.js
        const binaryUnits = document.querySelectorAll('.binary-unit');
        const positions = Array.from(binaryUnits).map(unit => {
            const rect = unit.getBoundingClientRect();
            return {
                x: rect.left + rect.width / 2,
                y: rect.top + rect.height / 2
            };
        });

        // Drawing Settings
        ctx.lineWidth = 0.7;
        
        for (let i = 0; i < positions.length; i++) {
            for (let j = i + 1; j < positions.length; j++) {
                const dx = positions[i].x - positions[j].x;
                const dy = positions[i].y - positions[j].y;
                const distance = Math.sqrt(dx * dx + dy * dy);

                // Only connect if dots are within "webbing range"
                if (distance < 180) {
                    ctx.beginPath();
                    
                    // Miles Morales Bio-Electric Yellow (#fbff00)
                    // The line fades out as the dots get further apart
                    const alpha = 1 - (distance / 180);
                    ctx.strokeStyle = `rgba(251, 255, 0, ${alpha * 0.4})`; 
                    
                    ctx.moveTo(positions[i].x, positions[i].y);
                    ctx.lineTo(positions[j].x, positions[j].y);
                    ctx.stroke();
                }
            }
        }
        requestAnimationFrame(drawSpiderWebs);
    }

    // Start the animation loop
    drawSpiderWebs();
})();